import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({request}) {
  return (
    <div>
      <Head>
        <title>Hulu - 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Results results={request}/>
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await (await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)).json()
  return{
    props: {request}
  }
}